import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("java")
    id("org.jetbrains.kotlin.jvm") version "2.0.21"
    id("org.jetbrains.intellij.platform") version "2.13.1"
}

group = providers.gradleProperty("pluginGroup").get()
version = providers.gradleProperty("pluginVersion").get()

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenCentral()
    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    intellijPlatform {
        intellijIdeaCommunity(providers.gradleProperty("platformVersion"))
        bundledPlugin("org.jetbrains.plugins.textmate")
    }
}

intellijPlatform {
    pluginConfiguration {
        id = providers.gradleProperty("pluginGroup")
        version = providers.gradleProperty("pluginVersion")
        ideaVersion {
            sinceBuild = providers.gradleProperty("pluginSinceBuild")
        }
    }
}

// The three TextMate bundles ship the SAME syntaxes/*.tmLanguage.json the
// VSCode extension uses (repo-root syntaxes/, regenerated by
// tools/build-grammars.mjs) - one grammar source for both IDEs. Only the
// bundles/*/info.plist wrapper files are JetBrains-specific, and those are
// checked in directly under src/main/resources since they never change.
//
// PluginPathManager.getPluginResource() (used by CgproTextMateBundleProvider)
// resolves against LOOSE files under the installed plugin's directory - NOT
// against the plugin jar's classpath resources. So bundles/ must NOT go
// through the normal main resources -> jar pipeline; it has to be copied
// straight into the sandbox/distribution plugin directory via
// prepareSandbox/prepareTestSandbox, the same way jetbrains-plugin-fss does
// it for its own TextMate bundle. (Symptom when this is wrong: TextMate logs
// "Cannot find referenced file `info.plist` in bundle ...tmbundle" and the
// grammar silently fails to load.)
val grammarsDir = rootDir.resolve("../syntaxes")

tasks.register<Copy>("copyGrammars") {
    into(layout.buildDirectory.dir("generated-resources/bundles"))
    from(grammarsDir.resolve("cgpl.tmLanguage.json")) { into("cgpl.tmbundle/Syntaxes") }
    from(grammarsDir.resolve("wssp.tmLanguage.json")) { into("wssp.tmbundle/Syntaxes") }
    from(grammarsDir.resolve("cgpro-data.tmLanguage.json")) { into("cgpro-data.tmbundle/Syntaxes") }
}

sourceSets {
    main {
        resources.exclude("bundles/**")
    }
}

tasks {
    prepareSandbox {
        dependsOn("copyGrammars")
        from("src/main/resources/bundles") { into(pluginName.map { "$it/bundles" }) }
        from(layout.buildDirectory.dir("generated-resources/bundles")) { into(pluginName.map { "$it/bundles" }) }
    }
    prepareTestSandbox {
        dependsOn("copyGrammars")
        from("src/main/resources/bundles") { into(pluginName.map { "$it/bundles" }) }
        from(layout.buildDirectory.dir("generated-resources/bundles")) { into(pluginName.map { "$it/bundles" }) }
    }
}

tasks.withType<KotlinCompile> {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_21)
    }
}
